### ISSUE TITLE
Create benchmarks / profiling

### ISSUE THREAD

**Issue by kris-brown** [AlgebraicJulia/CSetAutomorphisms.jl#8]
Potential starting point: https://opensourc.es/blog/benchmarking-and-profiling-julia-code/

**Comment by epatters** [comment]
You could also look at Catlab for one example of how to set up the benchmark infrastructure: https://github.com/AlgebraicJulia/Catlab.jl/tree/master/benchmark

**Comment by kris-brown** [comment]
addressed by #11
