### ISSUE TITLE
Compare benchmarks to nauty/traces

### ISSUE THREAD

**Issue by kris-brown** [AlgebraicJulia/CSetAutomorphisms.jl#9]
To understand how the julia implementation of the algorithm is doing, the process of converting a CSet to a graph and  making an external call to nauty/traces should be automated. As a first step, this pipeline should be built for the CSet of directed graphs.

**Comment by epatters** [comment]
For interfacing with Nauty, you might find this package helpful: https://github.com/bovine3dom/Nauty.jl I haven't tried it before. Last I checked, it needed to be upgraded to Julia v1, but I see some fairly recent commits.
